services:
  postgres:
    image: postgres:latest
    container_name: aIMovieCharacterChatbotPSQL
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma


volumes:
  postgres_data:
  chroma_data:

